CREATE TABLE PESSOA (
	codigo INTEGER PRIMARY KEY, 
	nome VARCHAR(300)
);

CREATE TABLE CONTATO (
	codigo INTEGER PRIMARY KEY, 
	FK_PESSOA_codigo INTEGER REFERENCES PESSOA(codigo), 
	tipo VARCHAR(100), 
	contato VARCHAR(300)
);

CREATE TABLE PESSOA_FISICA (
	cpf CHAR(14) PRIMARY KEY,
	FK_PESSOA_codigo INTEGER REFERENCES PESSOA(codigo)
);

CREATE TABLE PESSOA_JURIDICA (
	cnpj VARCHAR(18) PRIMARY KEY,
	FK_PESSOA_codigo INTEGER REFERENCES PESSOA(codigo)
);

CREATE TABLE ENDERECO (
	codigo INTEGER PRIMARY KEY,
	cep CHAR(9),
	uf VARCHAR(19),
	cidade VARCHAR(80),
	bairro VARCHAR(100),
	tipo_logradouro VARCHAR(20),
	logradouro VARCHAR(200),
	numero_imovel INTEGER,
	complemento VARCHAR(255),
	FK_PESSOA_FISICA_cpf CHAR(18) REFERENCES PESSOA_FISICA(cpf)
);

CREATE TABLE PEDIDO (
	codigo INTEGER PRIMARY KEY,
	dt_compra DATE,
	metodo_pagamento VARCHAR(50),
	FK_PESSOA_FISICA_cpf CHAR(18) REFERENCES PESSOA_FISICA(cpf)
);

CREATE TABLE PRODUTO (
	codigo INTEGER PRIMARY KEY,
	preco_venda FLOAT,
	preco_compra FLOAT,
	nome VARCHAR(200)
);

CREATE TABLE VEICULO (
	placa CHAR(8) PRIMARY KEY,
	tipo_veiculo VARCHAR(50),
	veiculo VARCHAR(80)
);

CREATE TABLE UTILIZA (
	FK_PESSOA_FISICA_cpf CHAR(18) REFERENCES PESSOA_FISICA(cpf),
	FK_VEICULO_placa CHAR(8) REFERENCES VEICULO(placa)
);

CREATE TABLE FORNECE (
	FK_PRODUTO_codigo INTEGER REFERENCES PRODUTO(codigo),
	FK_PESSOA_JURIDICA_cnpj CHAR(18) REFERENCES PESSOA_JURIDICA(cnpj)
);

CREATE TABLE CONTEM (
	FK_PEDIDO_codigo INTEGER REFERENCES PEDIDO(codigo),
	FK_PRODUTO_codigo INTEGER REFERENCES PRODUTO(codigo),
	qtd INTEGER
);

CREATE TABLE RESERVA (
	FK_PESSOA_FISICA_cpf CHAR(18) REFERENCES PESSOA_FISICA(cpf),
	FK_PEDIDO_codigo INTEGER REFERENCES PEDIDO(codigo)
);
