CREATE TABLE PESSOA (
	codigo INTEGER PRIMARY KEY, 
	nome VARCHAR(300)
);

CREATE TABLE CONTATO (
	codigo INTEGER PRIMARY KEY, 
	FK_PESSOA_codigo INTEGER REFERENCES PESSOA(codigo), 
	tipo VARCHAR(100), 
	contato VARCHAR(300)
);

CREATE TABLE PESSOA_FISICA (
	cpf CHAR(14) PRIMARY KEY,
	FK_PESSOA_codigo INTEGER REFERENCES PESSOA(codigo)
);

CREATE TABLE CLIENTE (
	CODIGO INTEGER PRIMARY KEY,
	FK_PESSOA_FISICA_CPF CHAR(14) REFERENCES PESSOA_FISICA(cpf),
	DATA_CADASTRO DATE
);

CREATE TABLE FUNCIONARIO (
	CODIGO INTEGER PRIMARY KEY,
	FK_PESSOA_FISICA_CPF CHAR(14) REFERENCES PESSOA_FISICA(cpf),
	SALARIO FLOAT
);

CREATE TABLE ENTREGADOR (
	CODIGO INTEGER PRIMARY KEY,
	FK_PESSOA_FISICA_CPF CHAR(14) REFERENCES PESSOA_FISICA(cpf),
	NUMERO_CNH BIGINT
);

CREATE TABLE PESSOA_JURIDICA (
	codigo INTEGER PRIMARY KEY,
	cnpj VARCHAR(18),
	FK_PESSOA_codigo INTEGER REFERENCES PESSOA(codigo)
);

CREATE TABLE ENDERECO (
	codigo INTEGER PRIMARY KEY,
	cep CHAR(9),
	uf VARCHAR(19),
	cidade VARCHAR(80),
	bairro VARCHAR(100),
	tipo_logradouro VARCHAR(20),
	logradouro VARCHAR(200),
	numero_imovel INTEGER,
	complemento VARCHAR(255),
	FK_CLIENTE_codigo INTEGER REFERENCES CLIENTE(codigo)
);

CREATE TABLE PEDIDO (
	codigo INTEGER PRIMARY KEY,
	dt_compra DATE,
	metodo_pagamento VARCHAR(50),
	FK_CLIENTE_CODIGO INTEGER REFERENCES CLIENTE(codigo)
);

CREATE TABLE PRODUTO (
	codigo INTEGER PRIMARY KEY,
	preco_venda FLOAT,
	nome VARCHAR(200)
);

CREATE TABLE VEICULO (
	placa CHAR(8) PRIMARY KEY,
	tipo_veiculo VARCHAR(50),
	veiculo VARCHAR(80)
);

CREATE TABLE RESERVA (
	FK_FUNCIONARIO_CODIGO INTEGER REFERENCES FUNCIONARIO(codigo),
	FK_PEDIDO_codigo INTEGER REFERENCES PEDIDO(codigo)
);
CREATE TABLE FORNECE (
	FK_PRODUTO_codigo INTEGER REFERENCES PRODUTO(codigo),
	FK_PESSOA_JURIDICA_codigo INTEGER REFERENCES PESSOA_JURIDICA(codigo),
	preco_venda FLOAT
);

CREATE TABLE CONTEM (
	FK_PEDIDO_codigo INTEGER REFERENCES PEDIDO(codigo),
	FK_PRODUTO_codigo INTEGER REFERENCES PRODUTO(codigo),
	qtd INTEGER
);

CREATE TABLE ENTREGA (
	FK_ENTREGADOR_CODIGO INTEGER REFERENCES ENTREGADOR(codigo),
	FK_PEDIDO_CODIGO INTEGER REFERENCES PEDIDO(codigo),
	FK_VEICULO_placa CHAR(8) REFERENCES VEICULO(placa)
);
